title: Shaokun Liu's Homepage
page-top-title: Shaokun Liu
top-section-bg-text: Artificial intelligence of things(AIOT)
home-subtitle: Shaokun Liu&ensp;|&ensp;刘少坤
copyright-text: '&copy;  Shaokun Liu 2023-2024. All Rights Reserved.'
